title: BAE
default_lang: en
author:
  name: 'Emilio Calderón, Fernanda Fajardo, Isabel Osegueda, Jordan Luna, Alberto Rojas'
taxonomies:
  - category
  - tag
metadata:
  description: 'Sitio Programa Bandera Azul Ecológica'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
